default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 30 } %>

development:
  <<: *default
  adapter: mysql2
  database: halogen
  # host: gc-mysql-ppp-do-user-9771742-0.b.db.ondigitalocean.com
  # username: doadmin
  # password: AVNS_881PPpp5Q3mr2rbyH68
  # port: 25060
  host: localhost
  username: ppp
  #password: ajay
  #url: mysql://doadmin:AVNS_881PPpp5Q3mr2rbyH68@gc-mysql-ppp-do-user-9771742-0.b.db.ondigitalocean.com:25060/defaultdb?ssl-mode=REQUIRED
  # database: defaultdb
  # host: console-staging-do-user-9771742-0.b.db.ondigitalocean
  # username: doadmin
  # password: AVNS_wYH8hY1NYPfwgWbzWp3
  # port: 25060
  #mysql2://doadmin:AVNS_wYH8hY1NYPfwgWbzWp3@console-staging-do-user-9771742-0.b.db.ondigitalocean.com:25060/defaultdb?ssl-mode=REQUIRED

test:
  <<: *default
  database: console_project_test
  host: localhost
  username: ppp


production:
  <<: *default
  database: console_project_production
  username: console_project
  password: <%= ENV["CONSOLE_PROJECT_DATABASE_PASSWORD"] %>
